# Generated by Django 6.0.4 on 2026-05-09 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0005_alter_review_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='description',
        ),
    ]
